function x = getspikes(fall,t,dt)
% function x = getspikes(fall,t,dt)
%
% Returns the number of spikes for the cells for a 
% given time interval.
%
% x = [1 ... cells], number of spikes for cell i for
%                    t -> t + dt
% fall               spike times of cell j.
%                    fall generated by 'cellfiring.m'   


x = zeros(size(fall,2),1); 
for i=1:size(fall,2)         
    s1 = locate(fall(:,i),t)   ; 
    s2 = locate(fall(:,i),t+dt);    
    x(i) = s2 -s1 ; 
end

